=== d-bl/bobbinwork/trunk/src/nl/BobbinWork/diagram/xml/bw.xsd
<?xml version='1.0' encoding="ISO-8859-1"?>
<xsd:schema xmlns="http://www.xs4all.nl/~falkink/lace/BobbinWork/bw.xsd"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.xs4all.nl/~falkink/lace/BobbinWork/bw.xsd"
            elementFormDefault="qualified"
            attributeFormDefault="qualified" 
>
<!-- Copyright 2004, J. Falkink-Pol

This file is part of BobbinWork.

BobbinWork is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

BobbinWork is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with BobbinWork.  If not, see <http://www.gnu.org/licenses/>.

-->

 <xsd:annotation>
  <xsd:documentation>
   The storage format reflects the working order for a lace maker.
   Lace makers keywords: thread, gimp, pair, pin, bobbin, stitch, cross, twist, pattern, repeat.
  </xsd:documentation>
 </xsd:annotation>

 <!--
   Basics
 -->

 <xsd:simpleType name="xy">
  <!--
    Co-ordinates, starting from the left upper corner.
    Signs are only allowed within copy elements,
    turning absolute coordinates into relative movements.
    -->
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="[+-]?[0-9]+,[+-]?[0-9]+"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="nm">
  <!--
    Select pairs or bobbins of the ancestor
    counting them from left to right, starting at 1.
    After each movement bobbins and pairs are recounted.
    For bobbins within a stitch the usual values are:
    2-3 for cross, either 1-2 or 3-4 for twist.
    Pairs treated as threads create exeptions.
    -->
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="[0-9]+\-[0-9]+"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="nrs">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+))*"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="color">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="([0-9A-F]{6}|red|green|blue|black|white|yellow|purple|orange|brown)"/>
   <!--
     000000=black  FFFFFF=white
     FF0000=red    00FF00=green  0000FF=blue
     FFFF00=yellow FF00FF=purple FF8000=orange 804000=brown
     -->
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="deco">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="(solid|dashes|dots|dashDot|dashDotDot|dashDashDot|Ztwist|Stwist)"/>
   <!-- Ztwist and Stwist may be too ambitious -->
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:complexType name="text">
   <xsd:simpleContent>
     <xsd:extension base="xsd:string">
       <xsd:attribute name="lang" type="xsd:string"/>
     </xsd:extension>
   </xsd:simpleContent>
 </xsd:complexType>

 <xsd:complexType name="style">
  <xsd:attribute  name="color"  type="color"               default="black"/>
  <xsd:attribute  name="width"  type="xsd:positiveInteger" default="1"/>
  <xsd:attribute  name="deco"   type="deco"                default="solid"/>
 </xsd:complexType>

 <xsd:complexType name="curve">
  <xsd:attribute  name="start"  type="xy"/>
  <xsd:attribute  name="c1"     type="xy"/>
  <xsd:attribute  name="c2"     type="xy"/>
  <xsd:attribute  name="end"    type="xy"/>
 </xsd:complexType>

 <!--
   Transformations
 -->

 <xsd:complexType name="meet">
  <!-- Overrides default adjustments connecting ends with starts. -->
  <xsd:choice>
   <xsd:element   name="pair"   type="curve"/>
   <xsd:element   name="back"   type="curve"/>
   <xsd:element   name="gimp"   type="curve"/>
   <xsd:element   name="front"  type="curve"/>
  </xsd:choice>
  <xsd:attribute  name="nr"     type="xsd:positiveInteger"/>
 </xsd:complexType>

 <xsd:complexType name="rotate">
  <!--
    With a and b instead of angle a rotation includes resizing.
    All 3 points on a strait line is a resize without rotation.
    -->
  <xsd:attribute  name="centre" type="xy" use="required"/>
  <xsd:attribute  name="angle"  type="xsd:integer"/>
  <xsd:attribute  name="a"      type="xy"/>
  <xsd:attribute  name="b"      type="xy"/>
 </xsd:complexType>

 <xsd:complexType name="mirror">
  <!--
    Mirror in the line through a and b.
    Note that back curves become front curves and vice versa,
    but starts don't become ends.
    -->
  <xsd:attribute  name="a"      type="xy" use="required"/>
  <xsd:attribute  name="b"      type="xy" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="move">
  <xsd:attribute  name="x"      type="xsd:integer" default="0"/>
  <xsd:attribute  name="y"      type="xsd:integer" default="0"/>
 </xsd:complexType>

 <xsd:complexType name="copy">
  <xsd:sequence                                 minOccurs="0" maxOccurs="unbounded" >
   <xsd:element   name="move"     type="move"   minOccurs="0" maxOccurs="1" />
   <xsd:element   name="rotate"   type="rotate" minOccurs="0" maxOccurs="1" />
   <xsd:element   name="meet"     type="meet"   minOccurs="0" maxOccurs="unbounded" />
   <!-- more to be developped, e.g. copy a rectangle into a fan -->
  </xsd:sequence>
  <xsd:attribute  name="pairs" type="nm"        use="required"/>
  <xsd:attribute  name="of"    type="xsd:IDREF" use="required"/>
 </xsd:complexType>

 <!--
   The essentials
 -->

 <xsd:complexType name="pin">
  <xsd:attribute  name="position" type="xy" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="bobbins">
  <!--
    Defaults:
    front.color = black;
    back.color  = grey;
    back.width  = largestOf (3 * front.width, 5 + front.width).
    back.deco   = front.deco = solid.
    -->
  <xsd:sequence>
   <xsd:element   name="thread" type="text"  minOccurs="0" maxOccurs="1" />
   <xsd:element   name="front"  type="style" minOccurs="0" maxOccurs="1" />
   <xsd:element   name="back"   type="style" minOccurs="0" maxOccurs="1" />
  </xsd:sequence>
  <xsd:attribute  name="nrs"    type="nrs" use="required"/>
  <xsd:attribute  name="id"     type="xsd:ID" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="switch">
  <xsd:sequence>
   <xsd:element   name="back"   type="curve" minOccurs="1" maxOccurs="1" />
   <xsd:element   name="gimp"   type="curve" minOccurs="0" maxOccurs="2"/>
   <xsd:element   name="front"  type="curve" minOccurs="1" maxOccurs="1" />
  </xsd:sequence>
  <xsd:attribute  name="bobbins" type="nm" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="stitch">
  <xsd:sequence>
   <xsd:element   name="title"  type="text"  minOccurs="0" maxOccurs="unbounded" />
   <xsd:element   name="pin"    type="pin"   minOccurs="0" maxOccurs="unbounded" />
   <!--
     The style basically concerns colors,
     for black-and-white prints 'deco' and 'width' can replaces colors.

     Use 'style' in an open or closed drawing.
     In case of an open+closed drawing:
     use 'style' if the stitch either starts and ends with twists,
     or starts and ends with cross-movements;
     otherwise use both 'open' and 'closed'.
     -->
   <xsd:element   name="style"  type="style" minOccurs="0" maxOccurs="1" />
   <xsd:element   name="pair"   type="curve" minOccurs="1" maxOccurs="unbounded" />
   <xsd:sequence                             minOccurs="1" maxOccurs="unbounded" >
    <xsd:element  name="twist"  type="switch" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element  name="cross"  type="switch" minOccurs="0" maxOccurs="unbounded" />
    <!-- Twist: Even thread over preceding thread.
         Cross: Odd thread over next thread
         Pairs used as threads and gimps cause exceptions.
         Gimps are drawn between back and front.

         In an open diagram stitches should end with a cross,
         trailing twists are drawn as cross marks in a pair diagram.
         In a closed diagram stitches should start with a cross,
         leading twists are drawn as cross marks in a pair diagram.
      -->
   </xsd:sequence>
  </xsd:sequence>
  <xsd:attribute  name="pairs"  type="nm" use="required"/>
  <xsd:attribute  name="id"     type="xsd:ID"/>
 </xsd:complexType>

 <xsd:complexType name="group">
  <!-- Twists at group level are allways drawn as cross marks on pair curves. -->
  <xsd:sequence>
   <xsd:element   name="title"  type="text"   minOccurs="0" maxOccurs="unbounded" />
   <xsd:sequence                              minOccurs="1" maxOccurs="unbounded" >
     <xsd:element name="twist"  type="switch" minOccurs="0" maxOccurs="unbounded" />
     <xsd:element name="group"  type="group"  minOccurs="0" maxOccurs="unbounded" />
     <xsd:element name="stitch" type="stitch" minOccurs="0" maxOccurs="unbounded" />
     <xsd:element name="copy"   type="copy"   minOccurs="0" maxOccurs="unbounded" />
   </xsd:sequence>
  </xsd:sequence>
  <xsd:attribute  name="pairs"  type="nm" use="required"/>
  <xsd:attribute  name="id"     type="xsd:ID"/>
 </xsd:complexType>

 <xsd:complexType name="diagram">
  <xsd:sequence>
   <xsd:element   name="title"  type="text"   minOccurs="0" maxOccurs="unbounded" />
   <xsd:element   name="group"  type="group"  minOccurs="0" maxOccurs="unbounded" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element     name="diagram"/>

</xsd:schema>

=== d-bl/bobbinwork/wiki/diagrams/plaits.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns="http://BobbinWork.googlecode.com/bw.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BobbinWork.googlecode.com bw.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude"
>
  <title>
    <value lang="en">Copyright 2009, J. Pol, some rights reserved: http://creativecommons.org/licenses/by/3.0/</value>
  </title>
  <xi:include href='http://bobbinwork.googlecode.com/svn/!svn/bc/569/trunk/src/main/resources/nl/BobbinWork/diagram/xml/basicStitches.xml'/>
  <group pairs="1001-1012" display="no">
    <title>
        <value lang="en">Library (building blocks for plait connections)</value>
        <value lang="nl">Bibliotheek (bouwstenen voor verbindingen in vlechten)</value>
        <value lang="de">Bibliothek (Bausteine fur Verbindungen von Flechter)</value>
    </title>
    <stitch pairs="1-6">
      <title><value lang="en">dummy</value></title>
      <style width="2" />
      <pair start="0,0" end="0,0" />
      <pair start="0,0" end="0,0" />
      <pair start="0,0" end="0,0" />
      <pair start="0,0" end="0,0" />
      <pair start="0,0" end="0,0" />
      <pair start="0,0" end="0,0" />
      <cross id="starC1" bobbins="3-6">
        <front start="-5,-2" c1="-3,0" c2="3,0" end="5,2" />
        <front start="-5,-2" c1="-3,0" c2="3,0" end="5,2" />
        <back start="5,-2" c1="3,0" c2="-3,0"  end="-5,2" />
        <back start="5,-2" c1="3,0" c2="-3,0"  end="-5,2" />
      </cross>
      <cross id="starC2" bobbins="7-10">
        <front start="-5,-2" c1="-3,0" c2="3,0" end="5,2" />
        <front start="-5,-2" c1="-3,0" c2="3,0" end="5,2" />
        <back start="5,-2" c1="3,0" c2="-3,0"  end="-5,2" />
        <back start="5,-2" c1="3,0" c2="-3,0"  end="-5,2" />
      </cross>
      <twist id="starT1" bobbins="1-4">
        <front start="5,-2" c1="3,0" c2="-3,0" end="-5,2" />
        <front start="5,-2" c1="3,0" c2="-3,0" end="-5,2" />
        <back start="-5,-2" c1="-3,0" c2="3,0"  end="5,2" />
        <back start="-5,-2" c1="-3,0" c2="3,0"  end="5,2" />
      </twist>
      <twist id="starT2" bobbins="5-8">
        <front start="5,-2" c1="3,0" c2="-3,0" end="-5,2" />
        <front start="5,-2" c1="3,0" c2="-3,0" end="-5,2" />
        <back start="-5,-2" c1="-3,0" c2="3,0"  end="5,2" />
        <back start="-5,-2" c1="-3,0" c2="3,0"  end="5,2" />
      </twist>
      <twist id="starT3" bobbins="9-12">
        <front start="5,-2" c1="3,0" c2="-3,0" end="-5,2" />
        <front start="5,-2" c1="3,0" c2="-3,0" end="-5,2" />
        <back start="-5,-2" c1="-3,0" c2="3,0"  end="5,2" />
        <back start="-5,-2" c1="-3,0" c2="3,0"  end="5,2" />
      </twist>
    </stitch>
    <stitch id="star" pairs="7-12">
      <title><value lang="en">three plait connection</value></title>
      <pair start="-25,-15"  end="25,15" />
      <pair start="-25,-15"  end="25,15" />
      <pair start="0,-30" end="0,30" />
      <pair start="0,-30" end="0,30" />
      <pair start="25,-15" end="-25,15" />
      <pair start="25,-15" end="-25,15" />

      <copy of="starT1"><move y="-30"  /><rotate centre="0,0" angle="-60" /></copy>
      <copy of="starT2"><move y="-30"  /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starT3"><move y="-30"  /><rotate centre="0,0" angle="60" /></copy>
  
      <copy of="starC1"><move y="-25" /><rotate centre="0,0" angle="-30" /></copy>
      <copy of="starC2"><move y="-25" /><rotate centre="0,0" angle="30" /></copy>
      <copy of="starT2"><move y="-15"  /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starC1"><move y="-15" /><rotate centre="0,0" angle="-60" /></copy>
      <copy of="starC2"><move y="-15" /><rotate centre="0,0" angle="60" /></copy>
  
      <copy of="starT1"><move y="0" x="-25" /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starT3"><move y="0" x="25" /><rotate centre="0,0" angle="0" /></copy>

      <copy of="starC1"><move y="15" /><rotate centre="0,0" angle="60" /></copy>
      <copy of="starC2"><move y="15" /><rotate centre="0,0" angle="-60" /></copy>
      <copy of="starT2"><move y="15"  /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starC1"><move y="25" /><rotate centre="0,0" angle="30" /></copy>
      <copy of="starC2"><move y="25" /><rotate centre="0,0" angle="-30" /></copy>

      <copy of="starT1"><move y="30"/><rotate centre="0,0" angle="60" /></copy>
      <copy of="starT2"><move y="30"/><rotate centre="0,0" angle="0" /></copy>
      <copy of="starT3"><move y="30"/><rotate centre="0,0" angle="-60" /></copy>
    </stitch>
  </group>
  <group id="x1" pairs="1-6">
    <title>
        <value lang="en">diagram</value>
        <value lang="nl">werktekening</value>
        <value lang="de">Arbeitszeichnung</value>
    </title>
    <group id="x2" pairs="1-6">
      <title><value lang="en">plaits</value></title>
    
      <new_bobbins nrs="5,7"><style color="#00FF00"></style></new_bobbins>
      <new_bobbins nrs="6,8"><style color="#FF0000"></style></new_bobbins>

      <copy of="ctctc" pairs="1-2"><move x="160" y="35"/><rotate centre="170,100" angle="-60" /></copy>
      <copy of="ctctc" pairs="3-4"><move x="160" y="35"/><rotate centre="170,100" angle="0" /></copy>
      <copy of="ctctc" pairs="5-6"><move x="160" y="35"/><rotate centre="170,100" angle="60" /></copy>
      <copy of="star" pairs="1-6"><move x="170" y="100"/></copy>
      <copy of="ctctc" pairs="1-2"><move x="160" y="135"/><rotate centre="170,100" angle="60" /></copy>
      <copy of="ctctc" pairs="3-4"><move x="160" y="135"/><rotate centre="170,100" angle="0" /></copy>
      <copy of="ctctc" pairs="5-6"><move x="160" y="135"/><rotate centre="170,100" angle="-60" /></copy>
     <!-- 
      -->

     <!-- 
      -->
    </group>
  </group>
</diagram>

=== d-bl/bobbinwork/trunk/src/nl/BobbinWork/grounds/grounds.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='http://www.xs4all.nl/~falkink/BobbinWork/bw.xsd'
>
<!-- Copyright 2008, J. Falkink-Pol
  
This file is part of BobbinWork.

BobbinWork is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

BobbinWork is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
  
You should have received a copy of the GNU General Public License
along with BobbinWork.  If not, see <http://www.gnu.org/licenses/>.
  
 -->
  <group pairs="1-1" display="no">
    <group id="flanders"  pairs="1-4">
      <group pairs="1-4">
        <!-- NE --><copy of="tc"   pairs="1-2"><rotate centre="10,10" angle="-45"/></copy>
        <!-- NW --><copy of="tc"   pairs="3-4"><rotate centre="10,10" angle="45"/><move x="60"/></copy>
        <!-- N  --><copy of="tctc" pairs="2-3"><move y="10" x="30"/></copy>
        <pin position="38,40"/>
        <!-- E  --><copy of="tc"   pairs="1-2"><move y="30" x="10"/></copy>
        <!-- W  --><copy of="tc"   pairs="3-4"><move y="30" x="50"/></copy>
        <!-- S  --><copy of="tctc" pairs="2-3"><move y="50" x="30"/></copy>
      </group>
    </group>
    <group id="spider" pairs="1-6">
      <!-- 1 --><copy of="ttctc"  pairs="3-4"><move x="50" y="10"/></copy>
      <!-- 2 --><copy of="llctc"  pairs="2-3"><move x="28" y="33"/></copy>
      <!-- 3 --><copy of="llctc"  pairs="1-2"><move x="10" y="55"/></copy>
      
      <!-- 4 --><copy of="rctc"  pairs="4-5"><move x="73" y="33"/></copy>
      <!-- 5 --><copy of="ctc"  pairs="3-4"><move x="50" y="43"/></copy>
      <!-- 6 --><copy of="ctc"  pairs="2-3"><move x="30" y="63"/></copy>
      
      <!-- 7 --><copy of="rctc"  pairs="5-6"><move x="90" y="55"/></copy>
      <!-- 8 --><copy of="ctc"  pairs="4-5"><move x="70" y="63"/></copy>
      <!-- 9 --><copy of="ctc"  pairs="3-4"><move x="50" y="70"/></copy>
      
      <!-- 10 --><copy of="ctc"  pairs="3-4"><move x="50" y="100"/></copy>
      <pin position="58,93"/>
      <!-- 11 --><copy of="ctc"  pairs="2-3"><move x="30" y="108"/></copy>
      <!-- 12 --><copy of="ctc"  pairs="1-2"><move x="10" y="115"/></copy>
      
      <!-- 13 --><copy of="ctc"  pairs="4-5"><move x="70" y="108"/></copy>
      <!-- 14 --><copy of="ctc"  pairs="3-4"><move x="50" y="125"/></copy>
      <!-- 15 --><copy of="ctc"  pairs="2-3"><move x="28" y="138"/></copy>
      
      <!-- 16 --><copy of="ctc"  pairs="5-6"><move x="90" y="115"/></copy>
      <!-- 17 --><copy of="ctc"  pairs="4-5"><move x="73" y="138"/></copy>
      <!-- 18 --><copy of="ctc"  pairs="3-4"><move x="50" y="160"/></copy>
    </group>
    <group id="vierge" pairs="1-4">
      <copy of="ctc" pairs="1-2"><rotate centre="8.2,8.4" angle="-55"/><move x="60" y="15"/></copy>
      <copy of="ctc" pairs="3-4"><rotate centre="8.2,8.4" angle="55"/><move x="140" y="15"/></copy>
      <group id="top" pairs="2-3">
        <copy of="ctc"  pairs="1-2"><move x="100" y="0"/></copy>
        <copy of="ctc"  pairs="1-2"><move x="100" y="32"/></copy>
        <pin position="108,25" />
      </group>
      <group id="left" pairs="3-4">
        <copy of="ctc"  pairs="1-2"><move x="140" y="40"/></copy>
        <copy of="ctc"  pairs="1-2"><move x="140" y="72"/></copy>
        <pin position="148,65" />
      </group>
      <copy of="ctc" pairs="2-3"><rotate centre="8.2,8.4" angle="55"/><move x="100" y="57"/></copy>
      <group id="left" pairs="1-2">
        <copy of="ctc"  pairs="1-2"><move x="60" y="40"/></copy>
        <copy of="ctc"  pairs="1-2"><move x="60" y="72"/></copy>
        <pin position="68,65" />
      </group>
      <group id="top" pairs="2-3">
        <copy of="ctc"  pairs="1-2"><move x="100" y="80"/></copy>
        <copy of="ctc"  pairs="1-2"><move x="100" y="112"/></copy>
        <pin position="108,105" />
      </group>
    </group>
    <group id="sGravenmoers" pairs="1-4">
      <copy of="ctc" pairs="1-2"><rotate centre="8.2,8.4" angle="-55"/><move x="60" y="15"/></copy>
      <copy of="ctc" pairs="3-4"><rotate centre="8.2,8.4" angle="55"/><move x="140" y="15"/></copy>
      <group id="top" pairs="2-3">
        <copy of="ctc"  pairs="1-2"><move x="100" y="0"/></copy>
        <copy of="ctc"  pairs="1-2"><move x="100" y="32"/></copy>
        <pin position="108,25" />
      </group>
      <group id="centre" pairs="1-4">
        <copy of="ctc"  pairs="3-4"><move x="140" y="40"/></copy>
        <copy of="ctc"  pairs="1-2"><move x="60" y="40"/></copy>
        <copy of="ctc" pairs="2-3"><rotate centre="8.2,8.4" angle="55"/><move x="100" y="57"/></copy>

        <copy of="ctc"  pairs="3-4"><move x="140" y="72"/></copy>
        <pin position="148,65" />
        <copy of="ctc"  pairs="1-2"><move x="60" y="72"/></copy>
        <pin position="68,65" />
      </group>
      <group id="top" pairs="2-3">
        <copy of="ctc"  pairs="1-2"><move x="100" y="80"/></copy>
        <copy of="ctc"  pairs="1-2"><move x="100" y="112"/></copy>
        <pin position="108,105" />
      </group>
    </group>
  </group>
</diagram>

=== d-bl/bobbinwork/wiki/diagrams/snow.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns="http://BobbinWork.googlecode.com/bw.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BobbinWork.googlecode.com bw.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude"
>
  <!-- This file is licensed under http://creativecommons.org/licenses/by/3.0/ 
    -->
  <xi:include href='http://bobbinwork.googlecode.com/svn-history/r278/trunk/src/nl/BobbinWork/diagram/xml/basicStitches.xml'/>
  <group id="snow" pairs="32761-32766">
    <pin position="58,0"/>
    <pin position="0,43"/>
    <pin position="116,43"/>
    <!-- 1 --><copy of="ttctc"  pairs="3-4"><move x="50" y="10"/></copy>
    <!-- 2 --><copy of="llctc"  pairs="2-3"><move x="28" y="33"/></copy>
    <!-- 3 --><copy of="llctc"  pairs="1-2"><move x="10" y="55"/></copy>
     
    <!-- 4 --><copy of="rctc"  pairs="4-5"><move x="73" y="33"/></copy>

    <!-- 5 --><copy of="tc"  pairs="3-4"><move x="50" y="43"/></copy>
    <!-- 6 --><copy of="tc"  pairs="2-3"><move x="30" y="63"/></copy>
      
    <!-- 7 --><copy of="rctc"  pairs="5-6"><move x="90" y="55"/></copy>
    <!-- 8 --><copy of="tc"  pairs="4-5"><move x="70" y="63"/></copy>
    <!-- 9 --><copy of="tc"  pairs="3-4"><move x="50" y="82"/></copy>
      
    <!-- 11 --><copy of="tc"  pairs="2-3"><move x="30" y="95"/></copy>
    <!-- 12 --><copy of="rctc"  pairs="1-2"><move x="10" y="115"/></copy>
      
    <!-- 13 --><copy of="tc"  pairs="4-5"><move x="70" y="95"/></copy>
    <!-- 14 --><copy of="tc"  pairs="3-4"><move x="50" y="110"/></copy>

    <!-- 15 --><copy of="rctc"  pairs="2-3"><move x="28" y="138"/></copy>
      
    <!-- 16 --><copy of="lctc"  pairs="5-6"><move x="90" y="115"/></copy>
    <!-- 17 --><copy of="lctc"  pairs="4-5"><move x="73" y="138"/></copy>
    <!-- 18 --><copy of="ctc"  pairs="3-4"><move x="50" y="160"/></copy>
  </group>
  <group pairs='1-34'>
    <copy of='snow' pairs='31-36'/>
    <copy of='snow' pairs='13-18'><move x='408' y='0'/></copy>
    <copy of='snow' pairs='9-14'><move x='272' y='100'/></copy>

    <copy of='snow' pairs='5-10'><move x='136' y='200'/></copy>
    <copy of='snow' pairs='1-6'><move x='0' y='300'/></copy>
    <copy of='snow' pairs='17-22'><move x='544' y='100'/></copy>
    <copy of='snow' pairs='13-18'><move x='408' y='200'/></copy>
    <copy of='snow' pairs='9-14'><move x='272' y='300'/></copy>
    <copy of='snow' pairs='5-10'><move x='136' y='400'/></copy>
    <copy of='snow' pairs='21-26'><move x='680' y='200'/></copy>
    <copy of='snow' pairs='17-22'><move x='544' y='300'/></copy>
    <copy of='snow' pairs='13-18'><move x='408' y='400'/></copy>

    <copy of='snow' pairs='9-14'><move x='272' y='500'/></copy>
    <copy of='snow' pairs='25-30'><move x='816' y='300'/></copy>
    <copy of='snow' pairs='21-26'><move x='680' y='400'/></copy>
    <copy of='snow' pairs='17-22'><move x='544' y='500'/></copy>
    <copy of='snow' pairs='13-18'><move x='408' y='600'/></copy>
  </group>
</diagram>

=== d-bl/bobbinwork/wiki/diagrams/braid-half-stitch.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns="http://BobbinWork.googlecode.com/bw.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BobbinWork.googlecode.com bw.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude"
>
  <title>
    <value lang="en">Copyright 2009, J. Pol, some rights reserved: http://creativecommons.org/licenses/by/3.0/</value>
  </title>
  <xi:include href='http://bobbinwork.googlecode.com/svn/!svn/bc/709/trunk/src/main/resources/nl/BobbinWork/diagram/xml/basicStitches.xml'/>
  <group pairs="1-9">
    <title>
      <value lang="en">Braid in half stitch</value>
      <value lang="nl">Bandje met netslagen</value>
    </title>

    <new_bobbins nrs="1,2,7,8,9,10"><style color="#0000FF"></style></new_bobbins>
    <new_bobbins nrs="3,4,5,6"><style color="#FF0000"><shadow color="#FFBBBB" width="5"/></style></new_bobbins>
    <group id="start" pairs="1-9">
      <title>
        <value lang="en">False footside</value>
        <value lang="nl">Opzet</value>
      </title>
      <stitch pairs="1-2">
        <title>
          <value lang="en">false footside left corner: three pair on two temporary pins, twisted cloth stitch</value>
          <value lang="nl">drie paar om twee hulpspelden, dubbele netslag</value>
        </title>
        <style color="#FF0000" width="2" />
        <pair start="30,110" end="45,120" />
        <pair start="40,100" end="30,120" />
        <copy of="F"><rotate centre="15,15" angle="25"/><move x="25" y="90"/></copy>
        <copy of="G"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
        <copy of="N"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
        <copy of="O"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
        <copy of="P"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
      </stitch>  
      <pin position="40,116"/>
      <copy of="ffs" pairs="3-4"><move x="075" y="85"/></copy><pin position="085,110"/>
      <copy of="ffs" pairs="5-6"><move x="135" y="85"/></copy><pin position="145,110"/>
      <copy of="ffs" pairs="7-8"><move x="195" y="85"/></copy><pin position="205,110"/>
    </group>
    <group id="x"  pairs="1-9">
      <title>
         <value lang="en">2 rows</value>
         <value lang="nl">2 toeren</value>
      </title>
      <group id="x1"  pairs="1-9">
        <title>
          <value lang="en">row 1</value>
          <value lang="nl">toer heen</value>
        </title>
        <copy of="tc_ltr" pairs="2-3"><move x="050" y="110"/></copy>
        <copy of="tc_ltr" pairs="3-4"><move x="080" y="110"/></copy>
        <copy of="tc_ltr" pairs="4-5"><move x="110" y="110"/></copy>
        <copy of="tc_ltr" pairs="5-6"><move x="140" y="110"/></copy>
        <copy of="tc_ltr" pairs="6-7"><move x="170" y="110"/></copy>
        <copy of="tc_ltr" pairs="7-8"><move x="200" y="110"/></copy>
        <pin position="235,140"/>
        <copy  of="hs-1" pairs="8-9"><move x="242" y="132"/></copy>
      </group> 
      <group id="x2"  pairs="1-9">
        <title>
          <value lang="en">row back</value>
          <value lang="nl">toer terug</value>
        </title>
        <copy of="tc_rtl" pairs="7-8"><move x="200" y="140"/></copy>
        <copy of="tc_rtl" pairs="6-7"><move x="170" y="140"/></copy>
        <copy of="tc_rtl" pairs="5-6"><move x="140" y="140"/></copy>
        <copy of="tc_rtl" pairs="4-5"><move x="110" y="140"/></copy>
        <copy of="tc_rtl" pairs="3-4"><move x="080" y="140"/></copy>
        <copy of="tc_rtl" pairs="2-3"><move x="050" y="140"/></copy>
        <copy of="fs-1"   pairs="1-2"><move x="022" y="162"/></copy>
      </group> 
    </group>
    <group id="x3"  pairs="1-9">
      <title>
         <value lang="en">2 rows</value>
         <value lang="nl">2 toeren</value>
      </title>
      <copy of="x1" pairs="1-9"><move y="60"/></copy>
      <copy of="x2"  pairs="1-9"><move y="60"/></copy>
    </group>
    <copy of="x3" pairs="1-9"><move y="60"/></copy>
    <copy of="x3" pairs="1-9"><move y="120"/></copy>
    <copy of="x3" pairs="1-9"><move y="180"/></copy>
    <copy of="x3" pairs="1-9"><move y="240"/></copy>
    <copy of="x3" pairs="1-9"><move y="300"/></copy>
    <copy of="x3" pairs="1-9"><move y="360"/></copy>
    <copy of="x3" pairs="1-9"><move y="420"/></copy>
    <copy of="x3" pairs="1-9"><move y="480"/></copy>
  </group>
</diagram>
