=== d-bl/bobbinwork/trunk/src/nl/BobbinWork/diagram/xml/bw.xsd
<?xml version='1.0' encoding="ISO-8859-1"?>
<xsd:schema xmlns="http://www.xs4all.nl/~falkink/lace/BobbinWork/bw.xsd"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.xs4all.nl/~falkink/lace/BobbinWork/bw.xsd"
            elementFormDefault="qualified"
            attributeFormDefault="qualified" 
>
<!-- Copyright 2004, J. Falkink-Pol

This file is part of BobbinWork.

BobbinWork is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

BobbinWork is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with BobbinWork.  If not, see <http://www.gnu.org/licenses/>.

-->

 <xsd:annotation>
  <xsd:documentation>
   The storage format reflects the working order for a lace maker.
   Lace makers keywords: thread, gimp, pair, pin, bobbin, stitch, cross, twist, pattern, repeat.
  </xsd:documentation>
 </xsd:annotation>

 <!--
   Basics
 -->

 <xsd:simpleType name="xy">
  <!--
    Co-ordinates, starting from the left upper corner.
    Signs are only allowed within copy elements,
    turning absolute coordinates into relative movements.
    -->
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="[+-]?[0-9]+,[+-]?[0-9]+"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="nm">
  <!--
    Select pairs or bobbins of the ancestor
    counting them from left to right, starting at 1.
    After each movement bobbins and pairs are recounted.
    For bobbins within a stitch the usual values are:
    2-3 for cross, either 1-2 or 3-4 for twist.
    Pairs treated as threads create exeptions.
    -->
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="[0-9]+\-[0-9]+"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="nrs">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+))*"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="color">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="([0-9A-F]{6}|red|green|blue|black|white|yellow|purple|orange|brown)"/>
   <!--
     000000=black  FFFFFF=white
     FF0000=red    00FF00=green  0000FF=blue
     FFFF00=yellow FF00FF=purple FF8000=orange 804000=brown
     -->
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="deco">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="(solid|dashes|dots|dashDot|dashDotDot|dashDashDot|Ztwist|Stwist)"/>
   <!-- Ztwist and Stwist may be too ambitious -->
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:complexType name="text">
   <xsd:simpleContent>
     <xsd:extension base="xsd:string">
       <xsd:attribute name="lang" type="xsd:string"/>
     </xsd:extension>
   </xsd:simpleContent>
 </xsd:complexType>

 <xsd:complexType name="style">
  <xsd:attribute  name="color"  type="color"               default="black"/>
  <xsd:attribute  name="width"  type="xsd:positiveInteger" default="1"/>
  <xsd:attribute  name="deco"   type="deco"                default="solid"/>
 </xsd:complexType>

 <xsd:complexType name="curve">
  <xsd:attribute  name="start"  type="xy"/>
  <xsd:attribute  name="c1"     type="xy"/>
  <xsd:attribute  name="c2"     type="xy"/>
  <xsd:attribute  name="end"    type="xy"/>
 </xsd:complexType>

 <!--
   Transformations
 -->

 <xsd:complexType name="meet">
  <!-- Overrides default adjustments connecting ends with starts. -->
  <xsd:choice>
   <xsd:element   name="pair"   type="curve"/>
   <xsd:element   name="back"   type="curve"/>
   <xsd:element   name="gimp"   type="curve"/>
   <xsd:element   name="front"  type="curve"/>
  </xsd:choice>
  <xsd:attribute  name="nr"     type="xsd:positiveInteger"/>
 </xsd:complexType>

 <xsd:complexType name="rotate">
  <!--
    With a and b instead of angle a rotation includes resizing.
    All 3 points on a strait line is a resize without rotation.
    -->
  <xsd:attribute  name="centre" type="xy" use="required"/>
  <xsd:attribute  name="angle"  type="xsd:integer"/>
  <xsd:attribute  name="a"      type="xy"/>
  <xsd:attribute  name="b"      type="xy"/>
 </xsd:complexType>

 <xsd:complexType name="mirror">
  <!--
    Mirror in the line through a and b.
    Note that back curves become front curves and vice versa,
    but starts don't become ends.
    -->
  <xsd:attribute  name="a"      type="xy" use="required"/>
  <xsd:attribute  name="b"      type="xy" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="move">
  <xsd:attribute  name="x"      type="xsd:integer" default="0"/>
  <xsd:attribute  name="y"      type="xsd:integer" default="0"/>
 </xsd:complexType>

 <xsd:complexType name="copy">
  <xsd:sequence                                 minOccurs="0" maxOccurs="unbounded" >
   <xsd:element   name="move"     type="move"   minOccurs="0" maxOccurs="1" />
   <xsd:element   name="rotate"   type="rotate" minOccurs="0" maxOccurs="1" />
   <xsd:element   name="meet"     type="meet"   minOccurs="0" maxOccurs="unbounded" />
   <!-- more to be developped, e.g. copy a rectangle into a fan -->
  </xsd:sequence>
  <xsd:attribute  name="pairs" type="nm"        use="required"/>
  <xsd:attribute  name="of"    type="xsd:IDREF" use="required"/>
 </xsd:complexType>

 <!--
   The essentials
 -->

 <xsd:complexType name="pin">
  <xsd:attribute  name="position" type="xy" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="bobbins">
  <!--
    Defaults:
    front.color = black;
    back.color  = grey;
    back.width  = largestOf (3 * front.width, 5 + front.width).
    back.deco   = front.deco = solid.
    -->
  <xsd:sequence>
   <xsd:element   name="thread" type="text"  minOccurs="0" maxOccurs="1" />
   <xsd:element   name="front"  type="style" minOccurs="0" maxOccurs="1" />
   <xsd:element   name="back"   type="style" minOccurs="0" maxOccurs="1" />
  </xsd:sequence>
  <xsd:attribute  name="nrs"    type="nrs" use="required"/>
  <xsd:attribute  name="id"     type="xsd:ID" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="switch">
  <xsd:sequence>
   <xsd:element   name="back"   type="curve" minOccurs="1" maxOccurs="1" />
   <xsd:element   name="gimp"   type="curve" minOccurs="0" maxOccurs="2"/>
   <xsd:element   name="front"  type="curve" minOccurs="1" maxOccurs="1" />
  </xsd:sequence>
  <xsd:attribute  name="bobbins" type="nm" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="stitch">
  <xsd:sequence>
   <xsd:element   name="title"  type="text"  minOccurs="0" maxOccurs="unbounded" />
   <xsd:element   name="pin"    type="pin"   minOccurs="0" maxOccurs="unbounded" />
   <!--
     The style basically concerns colors,
     for black-and-white prints 'deco' and 'width' can replaces colors.

     Use 'style' in an open or closed drawing.
     In case of an open+closed drawing:
     use 'style' if the stitch either starts and ends with twists,
     or starts and ends with cross-movements;
     otherwise use both 'open' and 'closed'.
     -->
   <xsd:element   name="style"  type="style" minOccurs="0" maxOccurs="1" />
   <xsd:element   name="pair"   type="curve" minOccurs="1" maxOccurs="unbounded" />
   <xsd:sequence                             minOccurs="1" maxOccurs="unbounded" >
    <xsd:element  name="twist"  type="switch" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element  name="cross"  type="switch" minOccurs="0" maxOccurs="unbounded" />
    <!-- Twist: Even thread over preceding thread.
         Cross: Odd thread over next thread
         Pairs used as threads and gimps cause exceptions.
         Gimps are drawn between back and front.

         In an open diagram stitches should end with a cross,
         trailing twists are drawn as cross marks in a pair diagram.
         In a closed diagram stitches should start with a cross,
         leading twists are drawn as cross marks in a pair diagram.
      -->
   </xsd:sequence>
  </xsd:sequence>
  <xsd:attribute  name="pairs"  type="nm" use="required"/>
  <xsd:attribute  name="id"     type="xsd:ID"/>
 </xsd:complexType>

 <xsd:complexType name="group">
  <!-- Twists at group level are allways drawn as cross marks on pair curves. -->
  <xsd:sequence>
   <xsd:element   name="title"  type="text"   minOccurs="0" maxOccurs="unbounded" />
   <xsd:sequence                              minOccurs="1" maxOccurs="unbounded" >
     <xsd:element name="twist"  type="switch" minOccurs="0" maxOccurs="unbounded" />
     <xsd:element name="group"  type="group"  minOccurs="0" maxOccurs="unbounded" />
     <xsd:element name="stitch" type="stitch" minOccurs="0" maxOccurs="unbounded" />
     <xsd:element name="copy"   type="copy"   minOccurs="0" maxOccurs="unbounded" />
   </xsd:sequence>
  </xsd:sequence>
  <xsd:attribute  name="pairs"  type="nm" use="required"/>
  <xsd:attribute  name="id"     type="xsd:ID"/>
 </xsd:complexType>

 <xsd:complexType name="diagram">
  <xsd:sequence>
   <xsd:element   name="title"  type="text"   minOccurs="0" maxOccurs="unbounded" />
   <xsd:element   name="group"  type="group"  minOccurs="0" maxOccurs="unbounded" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element     name="diagram"/>

</xsd:schema>

=== d-bl/bobbinwork/wiki/diagrams/sym-braid.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns="http://BobbinWork.googlecode.com/bw.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BobbinWork.googlecode.com bw.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude"
>
  <title>
    <value lang="en">Copyright 2010, J. Pol, some rights reserved: http://creativecommons.org/licenses/by/3.0/</value>
  </title>
  <xi:include href='http://bobbinwork.googlecode.com/svn/!svn/bc/562/trunk/src/main/resources/nl/BobbinWork/diagram/xml/basicStitches.xml'/>
  <group pairs="1-9">
    <title>
      <value lang="en">Symmetrical Braid</value>
      <value lang="nl">Symetrisch Bandje</value>
    </title>

    <group id="x"  pairs="1-6">
      <title>
         <value lang="en">2 rows</value>
         <value lang="nl">2 toeren</value>
      </title>
      <copy of="tctc" pairs="1-2"><move x="50" y="50"/></copy>
      <pin position="75,57"/>
      <!-- 
       -->
      <copy of="tc_ltr" pairs="2-3"><move x="70" y="50"/></copy>
      <copy of="tctc" pairs="5-6"><move x="150" y="50"/></copy>
      <pin position="142,57"/>
      <copy of="tc_rtl" pairs="4-5"><move x="120" y="50"/></copy>
      <copy of="tc" pairs="3-4"><move x="100" y="70"/></copy>
      <copy of="tc_ltr" pairs="4-5"><move x="120" y="75"/></copy>
      <copy of="tc_rtl" pairs="2-3"><move x="70" y="75"/></copy>
    </group>
    <copy of="x" pairs="1-6"><move y="55"/></copy>
    <copy of="x" pairs="1-6"><move y="110"/></copy>
    <copy of="x" pairs="1-6"><move y="165"/></copy>
    <copy of="x" pairs="1-6"><move y="220"/></copy>
  </group>
</diagram>

=== d-bl/bobbinwork/wiki/diagrams/braid-row-cloth-row-half-stitch.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns="http://BobbinWork.googlecode.com/bw.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BobbinWork.googlecode.com bw.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude"
>
  <title>
    <value lang="en">Copyright 2009, J. Pol, some rights reserved: http://creativecommons.org/licenses/by/3.0/</value>
  </title>
  <xi:include href='http://bobbinwork.googlecode.com/svn/!svn/bc/562/trunk/src/main/resources/nl/BobbinWork/diagram/xml/basicStitches.xml'/>
  <group pairs="1-9">
    <title>
      <value lang="en">Braid with alternating rows of cloth and half stitch</value>
      <value lang="nl">Bandje met afwisselende rijen met linnenslagen en netslagen</value>
    </title>

    <new_bobbins nrs="1,2,7,8,9,10"><style color="#0000FF"/></new_bobbins>
    <new_bobbins nrs="3,4,5,6"><style color="#FF0000"><shadow color="#FFBBBB" width="5"/></style></new_bobbins>
    <group pairs="1-9">
      <title>
        <value lang="en">False footside</value>
        <value lang="nl">Opzet</value>
      </title>
      <stitch pairs="1-2">
        <title>
          <value lang="en">false footside left corner: three pair on two temporary pins, twisted cloth stitch</value>
          <value lang="nl">drie paar om twee hulpspelden, dubbele netslag</value>
        </title>
        <style color="#FF0000" width="2" />
        <pair start="30,110" end="45,120" />
        <pair start="40,100" end="30,120" />
        <copy of="F"><rotate centre="15,15" angle="25"/><move x="25" y="90"/></copy>
        <copy of="G"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
        <copy of="N"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
        <copy of="O"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
        <copy of="P"><rotate centre="15,15" angle="-20"/><move x="25" y="100"/></copy>
      </stitch>  
      <pin position="40,116"/>
      <copy of="ffs" pairs="3-4"><move x="075" y="85"/></copy><pin position="085,110"/>
      <copy of="ffs" pairs="5-6"><move x="135" y="85"/></copy><pin position="145,110"/>
      <copy of="ffs" pairs="7-8"><move x="195" y="85"/></copy><pin position="205,110"/>
    </group>
    <group id="x1"  pairs="1-9">
      <title>
        <value lang="en">row 1</value>
        <value lang="nl">toer heen</value>

      </title>
      <copy of="tc_ltr" pairs="2-3"><move x="050" y="110"/></copy>
      <copy of="tc_ltr" pairs="3-4"><move x="080" y="110"/></copy>

      <copy of="tc_ltr" pairs="4-5"><move x="110" y="110"/></copy>
      <copy of="tc_ltr" pairs="5-6"><move x="140" y="110"/></copy>
      <copy of="tc_ltr" pairs="6-7"><move x="170" y="110"/></copy>
      <copy of="tc_ltr" pairs="7-8"><move x="200" y="110"/></copy>
      <copy of="hs-1" pairs="8-9"><move x="242" y="132"/></copy>
      <pin position="235,140"/>
    </group> 
    <group id="x2"  pairs="1-9">
      <title>
        <value lang="en">row back</value>
        <value lang="nl">toer terug</value>
      </title>
      <group pairs="7-8">
        <title>
          <value lang="en">first cloth stitch</value>
          <value lang="nl">eerste linnenslag</value>
        </title>
        <copy of="r1" pairs="2"><rotate centre="10,10" angle="45"/><move x="205" y="150"/></copy>
        <group id="l-ctc" pairs="1-2">
          <title>
            <value lang="en">twist passive, cloth stitch</value>
            <value lang="nl">draai hangend paar, linnenslag</value>
          </title>
          <copy of="l1" pairs="1"><rotate centre="10,10" angle="45"/><move x="205" y="150"/></copy>
          <copy of="ctc" pairs="1-2"><rotate centre="10,10" angle="45"/><move x="205" y="150"/></copy>
        </group>
      </group>
      <copy of="l-ctc" pairs="6-7"><move x="-30"/></copy>
      <copy of="l-ctc" pairs="5-6"><move x="-60"/></copy>
      <copy of="l-ctc" pairs="4-5"><move x="-90"/></copy>
      <copy of="l-ctc" pairs="3-4"><move x="-120"/></copy>
      <copy of="l-ctc" pairs="2-3"><move x="-150"/></copy>
      <!-- annotation>
        <value lang="en">odd number of twist on one side to maintain couloured workers</value>
        <value lang="nl"><![CDATA[aan <i>&euml;&euml;n</i> kant een oneven aantal draaien om de gekleeurede lopers in het spel
                         te houden]]></value>
      </annotation-->
      <copy of="fs-1"   pairs="1-2"><move x="022" y="162"/></copy>
      <pin position="50,170"/>
    </group> 
    
    <group id="x3"  pairs="1-9">
      <title>
         <value lang="en">2 rows</value>
         <value lang="nl">2 toeren</value>
      </title>
      <copy of="x1" pairs="1-9"><move y="60"/></copy>
      <copy of="x2"  pairs="1-9"><move y="60"/></copy>
    </group>

    <copy of="x3" pairs="1-9"><move y="60"/></copy>
    <copy of="x3" pairs="1-9"><move y="120"/></copy>
    <copy of="x3" pairs="1-9"><move y="180"/></copy>
    <copy of="x3" pairs="1-9"><move y="240"/></copy>
    <copy of="x3" pairs="1-9"><move y="300"/></copy>
    <copy of="x3" pairs="1-9"><move y="360"/></copy>
    <copy of="x3" pairs="1-9"><move y="420"/></copy>
    <copy of="x3" pairs="1-9"><move y="480"/></copy>
    <copy of="x3" pairs="1-9"><move y="540"/></copy>

    <copy of="x3" pairs="1-9"><move y="600"/></copy>
    <copy of="x3" pairs="1-9"><move y="660"/></copy>
    <copy of="x3" pairs="1-9"><move y="720"/></copy>
    <copy of="x3" pairs="1-9"><move y="780"/></copy>
    <copy of="x3" pairs="1-9"><move y="840"/></copy>
    <copy of="x3" pairs="1-9"><move y="900"/></copy>
  </group>
</diagram>

=== d-bl/bobbinwork/wiki/diagrams/stars.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns="http://BobbinWork.googlecode.com/bw.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BobbinWork.googlecode.com bw.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude"
>
  <title>
    <value lang="en">Copyright 2009, J. Pol, some rights reserved: http://creativecommons.org/licenses/by/3.0/</value>
  </title>
  <group pairs="1" display="no">
    <title>
        <value lang="en">Library (building blocks for the diagram)</value>
        <value lang="nl">Bibliotheek (bouwstenen voor de werktekening)</value>
        <value lang="de">Bibliothek (Bausteine fur Arbeitszeichnungen)</value>
    </title>
    <stitch pairs="1-3">
      <title><value lang="en"></value></title>
      <style width="2" />
      <pair start="0,0" end="0,0" />
      <pair start="0,0" end="0,0" />
      <cross id="starC1" bobbins="2-3">
        <front start="-3,-1" c1="-2,0" c2="2,0" end="3,1" />
        <back start="3,-1" c1="2,0" c2="-2,0"  end="-3,1" />
      </cross>
      <cross id="starC2" bobbins="4-5">
        <front start="-3,-1" c1="-2,0" c2="2,0" end="3,1" />
        <back start="3,-1" c1="2,0" c2="-2,0"  end="-3,1" />
      </cross>
      <twist id="starT1" bobbins="1-2">
        <front start="3,-1" c1="2,0" c2="-2,0" end="-3,1" />
        <back start="-3,-1" c1="-2,0" c2="2,0"  end="3,1" />
      </twist>
      <twist id="starT2" bobbins="3-4">
        <front start="3,-1" c1="2,0" c2="-2,0" end="-3,1" />
        <back start="-3,-1" c1="-2,0" c2="2,0"  end="3,1" />
      </twist>
      <twist id="starT3" bobbins="5-6">
        <front start="3,-1" c1="2,0" c2="-2,0" end="-3,1" />
        <back start="-3,-1" c1="-2,0" c2="2,0"  end="3,1" />
      </twist>
    </stitch>
    <stitch id="star" pairs="3-5">
      <pair start="-15,-8"  end="15,8" />
      <pair start="0,-22" end="0,22" />
      <pair start="15,-8" end="-15,8" />

      <copy of="starT1"><move y="-22"  /><rotate centre="0,0" angle="-60" /></copy>
      <copy of="starT2"><move y="-22"  /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starT3"><move y="-22"  /><rotate centre="0,0" angle="60" /></copy>
  
      <copy of="starC1"><move y="-17" /><rotate centre="0,0" angle="-30" /></copy>
      <copy of="starC2"><move y="-17" /><rotate centre="0,0" angle="30" /></copy>
      <copy of="starT2"><move y="-10"  /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starC1"><move y="-10" /><rotate centre="0,0" angle="-60" /></copy>
      <copy of="starC2"><move y="-10" /><rotate centre="0,0" angle="60" /></copy>
  
      <copy of="starT1"><move y="0" x="-17" /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starT3"><move y="0" x="17" /><rotate centre="0,0" angle="0" /></copy>

      <copy of="starC1"><move y="10" /><rotate centre="0,0" angle="60" /></copy>
      <copy of="starC2"><move y="10" /><rotate centre="0,0" angle="-60" /></copy>
      <copy of="starT2"><move y="10"  /><rotate centre="0,0" angle="0" /></copy>
      <copy of="starC1"><move y="17" /><rotate centre="0,0" angle="30" /></copy>
      <copy of="starC2"><move y="17" /><rotate centre="0,0" angle="-30" /></copy>

      <copy of="starT1"><move y="22"/><rotate centre="0,0" angle="60" /></copy>
      <copy of="starT2"><move y="22"/><rotate centre="0,0" angle="0" /></copy>
      <copy of="starT3"><move y="22"/><rotate centre="0,0" angle="-60" /></copy>
    </stitch>
  </group>
  <group pairs="2">
    <title>
        <value lang="en">diagram</value>
        <value lang="nl">werktekening</value>
        <value lang="de">Arbeitszeichnung</value>
    </title>
    <group pairs="1-12">
      <new_bobbins nrs="5,6,15,16,19,20,21,22"><style color="#0000FF"></style></new_bobbins>
      <new_bobbins nrs="9,10,11,12,13,14"><style color="#00FF00"></style></new_bobbins>
      <new_bobbins nrs="1,2,3,4,7,8,17,18"><style color="#FF0000"></style></new_bobbins>
      <copy of="star" pairs="5-7"><move x="165" y="35"/></copy>

      <copy of="star" pairs="3-5"><move x="100" y="75"/></copy>
      <copy of="star" pairs="7-9"><move x="230" y="75"/></copy>

      <copy of="star" pairs="1-3"><move x="35" y="115"/></copy>
      <copy of="star" pairs="5-7"><move x="165" y="115"/></copy>
      <copy of="star" pairs="9-11"><move x="295" y="115"/></copy>

      <copy of="star" pairs="3-5"><move x="100" y="155"/></copy>
      <copy of="star" pairs="7-9"><move x="230" y="155"/></copy>

      <copy of="star" pairs="5-7"><move x="165" y="195"/></copy>
     <!-- 
      -->
    </group>
  </group>
</diagram>

=== d-bl/bobbinwork/examples/trapgevel.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagram
  xmlns="http://BobbinWork.googlecode.com/bw.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://BobbinWork.googlecode.com bw.xsd"
  xmlns:xi="http://www.w3.org/2001/XInclude"
>
  <title>
    <value lang="en">Copyright 2009, J. Pol, some rights reserved: http://creativecommons.org/licenses/by/3.0/</value>
  </title>
  <xi:include href='http://bobbinwork.googlecode.com/svn/!svn/bc/709/trunk/src/main/resources/nl/BobbinWork/diagram/xml/basicStitches.xml'/>
  <group pairs="1-15" display="yes">
    <new_bobbins nrs="3-8,13-16"><style color="#0000FF"/></new_bobbins>
    <new_bobbins nrs="9-12"><style color="#FF0000"/></new_bobbins>
    <new_bobbins nrs="17-18,23-24"><style color="#993333"/></new_bobbins>
    <new_bobbins nrs="19-22"><style color="#44CC44" width="3"><shadow color="#DDFFDD" width="9"/></style></new_bobbins>
    <title>
      <value lang="nl">Opzet trapgevel</value>
      <value lang="nl">Start s staircase</value>
    </title>
    <copy of="bothGimps" pairs="10-11"><move x="300" y="110"/></copy>
    <group id="top" pairs="8-10">
      <title><value lang="en"> </value></title>
      <copy of="ffs" pairs="1-2"><move x="265" y="85"/></copy>
      <copy of="gRTL" pairs="2-3"><move x="287" y="110"/></copy>
      <copy of="gRTL" pairs="1-2"><move x="262" y="110"/></copy>
    </group>
    <group id="hoek" pairs="4-9">
      <title><value lang="en"> </value></title>
      <copy of="top" pairs="3-5"><move x="-60" y="0"/></copy>
      <copy of="vg" pairs="5-6"><move x="236" y="130"/></copy>
      <copy of="ffsL" pairs="1-2"><move x="135" y="90"/></copy>
      <copy of="gRTL" pairs="2-3"><rotate centre="0,5" angle="-50"/><move x="169" y="117"/></copy>
      <copy of="vg" pairs="3-4"><move x="181" y="130"/></copy>
      <copy of="vg" pairs="4-5"><move x="211" y="155"/></copy>
      <group pairs="1-3">
        <title>
          <value lang="nl">door sierdraad, randslag en terug</value>
        </title>
        <copy of="gLTR" pairs="2-3"><rotate centre="0,5" angle="90"/><move x="165" y="146"/></copy>
        <copy of="fs-1" pairs="1-2"><move x="133" y="156"/></copy>
        <copy of="gRTL" pairs="2-3"><rotate centre="0,5" angle="-90"/><move x="163" y="170"/></copy>
      </group>
      <copy of="vg" pairs="3-4"><move x="181" y="180"/></copy>
      <group pairs="1-3">
        <title>
          <value lang="nl">binnenhoek</value>
        </title>
        <copy of="gLTR" pairs="2-3"><rotate centre="2,9" angle="90"/><move x="165" y="188"/></copy>
        <group pairs="1-2">
          <group pairs="1-4">
            <title><value lang="en"> </value></title>
            <copy of="ll" pairs="1"><rotate centre="10,10" angle="45"/><move x="128" y="190"/></copy>
            <copy of="ffsLI" pairs="1-3"><move x="138" y="188"/></copy>
            <title><value lang="en"> </value></title>
            <copy of="gRTL" pairs="3-4"><rotate centre="0,5" angle="-60"/><move x="165" y="215"/></copy>
            <copy of="gRTL" pairs="2-3"><move x="141" y="224"/></copy>
          </group>
        </group>
      </group>
    </group>
    <group id="hoek1" pairs="8-13">
      <title><value lang="en"> </value></title>
      <copy of="ffsR" pairs="5-6"><move x="340" y="90"/></copy>
      <copy of="gLTR" pairs="4-5"><rotate centre="0,7" angle="45"/><move x="321" y="116"/></copy>
      <copy of="vg" pairs="3-4"><move x="295" y="130"/></copy>
      <group pairs="4-6">
        <title>
          <value lang="nl">door sierdraad, randslag en terug</value>
        </title>
        <copy of="gRTL" pairs="1-2"><rotate centre="0,7" angle="-90"/><move x="330" y="142"/></copy>
        <copy of="r" pairs="3"><rotate centre="10,10" angle="-45"/><move x="352" y="130"/></copy>
        <copy of="hs-r" pairs="2-3"><move x="348" y="155"/></copy>
        <pin position="342,163"/>
      </group>
    </group>
    <copy of="vg" pairs="9-10"><move x="265" y="155"/></copy>
    <copy of="vg" pairs="8-9"><move x="240" y="180"/></copy>
    <copy of="vg" pairs="7-8"><move x="215" y="205"/></copy>
    <copy of="hoek" pairs="1-5"><move x="-113" y="110"/></copy>
    <!-- hack: create space for the animation
    <copy of="l" pairs="3"><move x="90" y="380"/></copy>
     -->
  </group>
</diagram>
